- Plugins.json
For the current small plugin that lets you change the actual Volumes of a specified device.
The [Audio Control](https://github.com/G4PLS/AudioControl) Plugin.
The Volume Display is currently being Developed and should later Display the current Volume of a Device.
> Added AudioControl Plugin to the store

- Plugins.json
Added the Version for 1.4.11-beta which contains the newest version of the [Plugin](https://github.com/G4PLS/AudioControl)
> Added newest Audio Plugin Version

- Plugins.json
- A few things went wrong while creating the Action
- Switched to Adw.ScaleRow which makes everything a lot easier and removes a Bug that didnt let you open the Action after creating it
- Updated the Locales
> Updated Version that removes some critical things

- Icons.json
Duplicate of #22 but to a different branch and different manifest.json.
> Add Font Awesome icons

- Plugins.json
> Add StreamControllerTwitchPlugin

- Plugins.json
> update twitch plugin version

- Plugins.json
> twitchplugin: update to 1.0.1

- Plugins.json
> Fix beta-5 issues

- Plugins.json
> feat(TwitchPlugin): Adds TwitchPlugin support for 1.5.0-beta.5

- Plugins.json
> feat(TwitchPlugin): Adds TwitchPlugin support for 1.5.0

- Plugins.json
> Updated version of HomeAssistantPlugin

- Plugins.json
> New version for HomeAssistantPlugin

- Plugins.json
> Updated version for HomeAssistantPlugin

- Plugins.json
> feat(twitch): update twitchcontroller to 1.0.2 release

- Plugins.json
> feat(twitch): update twitchcontroller to 1.0.3 release

- Plugins.json
Reverts StreamController/StreamController-Store#49
> Revert "Silent swordmaiden xivdeck plugin"

- Plugins.json
I also added a new store thumbnail to better match the other apps' banners
> Update XIVDeck to 1.0.1

- Plugins.json
https://github.com/SilentSwordmaiden/StreamController-XIVDeck-Plugin/releases/tag/v1.1.2
> Update xivdeck plugin to v1.1.2

- Plugins.json
> Updated HomeAssistantPlugin (Option to customize icons)

- Icons.json
> Add Tabler.io iconpack

- Plugins.json
> Updated HomeAssistantPlugin (show person icons in state "home" in yellow)

- Plugins.json
> fix(discord): updating discord plugin version

- Plugins.json
> Update discord plugin

- Plugins.json
> Updated HomeAssistantPlugin (Allowed usage of self-signed certificates)

- Plugins.json
Tested `get_device` returning None by having the function return None by default while testing
> Conf(Plugins): Some more small fixes and some additional logging

- Plugins.json
https://github.com/ImDevinC/StreamControllerDiscordPlugin/releases/tag/v1.2.0
> Update discord to 1.2.0

- Plugins.json
- [x ] I tested my changes or release
- [ x] I agree to the [terms of service](https://streamcontroller.github.io/docs/latest/plugin_dev/submitting/terms/)
> Add mixbus plugin

- Plugins.json
-  Hopefully all the problems with the store installation in a flatak environment are fixed
- There were some problems in the settings (wrong dfault value and the spinners did not update when entering numbers)
> Fixed several bugs with the flatpak installation and configuration

- Plugins.json
> Add Elgato Key Light plugin

- Plugins.json
> Update ElgatoKeyLight to 0.1.4

- Plugins.json
Feature: Added connection status banner
> Update ElgatoKeyLight to 0.2.1

- Plugins.json
- [x ] I agree to the [terms of service](https://streamcontroller.github.io/docs/latest/plugin_dev/submitting/terms/)
> Update twitch to 1.2.0

- Plugins.json
> Update ElgatoKeyLight to 0.3.0

- Plugins.json
> feat(Plugins): add veadosc v1.0.0

- Plugins.json
> Update Twitch to 1.3.0

- Plugins.json
- Tested in raw Py env, with clean(ish) data dir in Flatpak, and with daily Flatpak env
> fix(veadosc): update to fix beta.8 crash

- Plugins.json
> Update twitch to 1.4.0

- Plugins.json
> Update Discord to 1.3.0

- Plugins.json
> Update Discord to 1.4.0

- Plugins.json
> Discord 1.4.2 release

- Plugins.json
Didnt test the Version but it should work, I intentionally added it under beta.7 as it should work under there
> Conf(Plugins): Added latest version of OS Plugin

- Plugins.json
> Updated HomeAssistantPlugin

- Icons.json
> Update add simple icons repo

- Plugins.json
> Updated HomeAssistantPlugin (Fixed crash after suspense)

- Plugins.json
> Updated HomeAssistantPlugin (Fixed message id not being incremented)

- Plugins.json
> Twitch 1.5.0 Release

- Plugins.json
> Twitch 1.5.1 release

- Plugins.json
> Release discord 1.4.3

- Plugins.json
> Discord 1.4.5 release

- Plugins.json
> Discord 1.4.6

- Plugins.json
> Add Spotify for StreamController Plugin

- Plugins.json
Found a first time startup bug
> Updated Soundboard to v1.1.1

- Plugins.json
> Add JetbrainsPlugin
